name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        target: [android] # On all platforms
        include:
          # Specify targets for each platform
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
          - runner: macos-latest
            target: ios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      ############## Setup toolchain ##############

      - name: Setup Flutter toolchain
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-cache"

      - name: Setup Protobuf compiler
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rinf command tool
        run: cargo install rinf

      ############## Setup specific target toolchain ##############

      - name: Setup Ninja, GTK3, GCC, GStreamer toolchain (Only Linux target)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y build-essential
          sudo apt install -y pkg-config
          sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

      - name: Setup Java toolchain (Only Android target)
        if: matrix.target == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      ############## Setup source ##############

      - name: Fetch dependencies
        run: flutter pub get

      - name: Generate message code
        run: rinf message

      ############## Build target ##############

      - name: Build Linux target
        if: matrix.target == 'linux'
        run: flutter build linux --verbose

      - name: Build Android target
        if: matrix.target == 'android'
        run: |
          flutter build apk --verbose
          flutter build appbundle --verbose

      - name: Build Windows target
        if: matrix.target == 'windows'
        run: flutter build windows --verbose

      - name: Build macOS target
        if: matrix.target == 'macos'
        run: flutter build macos --verbose

      - name: Build iOS target
        if: matrix.target == 'ios'
        run: flutter build ios --no-codesign --verbose

      ############## Upload artifacts ##############
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runner }}_${{ matrix.target }}
          path: |
            build/${{ matrix.target }}
