name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        target: [android] # On all platforms
        include:
          # Specify targets for each platform
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
          - runner: macos-latest
            target: ios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-cache"

      - name: Setup Protobuf compiler
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rinf CLI tool
        run: cargo install rinf

      - name: Setup Ninja and GTK3 toolchain (Only Linux target)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Java toolchain (Only Android target)
        if: matrix.target == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build example Flutter app
        if: matrix.target == 'linux'
        run: flutter build linux --verbose

      - name: Build example Flutter app
        if: matrix.target == 'android'
        run: |
          flutter build apk --verbose
          flutter build appbundle --verbose

      - name: Build example Flutter app
        if: matrix.target == 'windows'
        run: flutter build windows --verbose

      - name: Build example Flutter app
        if: matrix.target == 'macos'
        run: flutter build macos --verbose

      - name: Build example Flutter app
        if: matrix.target == 'ios'
        run: flutter build ios --no-codesign --verbose
